export const MOCK_CARS = [
  {
    _id: "mock1",
    name: "Maruti Suzuki Swift",
    brand: "Maruti Suzuki",
    price: 6.2,
    onRoadPrice: 7.1,
    category: "Hatchback",
    fuelType: "Petrol",
    transmission: "Manual",
    seatingCapacity: 5,
    mileage: 22.4,
    safetyRating: 3,
    image: "/cars/swift.jpg",
    gallery: ["/cars/swift.jpg"],
    engine: "1.2L Z-Series 3-Cylinder Petrol",
    horsepower: 80,
    torque: 112,
    topSpeed: 165,
    airbags: 6,
    adas: false,
    maintenanceCostPerYear: 5000,
    description: "The Maruti Suzuki Swift is India's favorite sporty hatchback, offering unmatched fuel efficiency, pocket-friendly maintenance, and a highly responsive manual gearbox.",
    pros: ["Exceptional fuel economy of 22.4 km/l", "Extremely pocket-friendly yearly maintenance", "Standard 6 airbags safety setup"],
    cons: ["3-Star safety rating is lower than competitors", "Cabin refinement could be slightly better at high speeds"],
  },
  {
    _id: "mock2",
    name: "Maruti Suzuki Baleno",
    brand: "Maruti Suzuki",
    price: 6.8,
    onRoadPrice: 7.8,
    category: "Hatchback",
    fuelType: "Petrol",
    transmission: "Automatic",
    seatingCapacity: 5,
    mileage: 22.9,
    safetyRating: 3,
    image: "/cars/baleno.jpg",
    gallery: ["/cars/baleno.jpg"],
    engine: "1.2L DualJet 4-Cylinder Petrol",
    horsepower: 89,
    torque: 113,
    topSpeed: 170,
    airbags: 6,
    adas: false,
    maintenanceCostPerYear: 5500,
    description: "The Maruti Suzuki Baleno is a premium hatchback featuring a spacious cabin, modern features like a head-up display and 360-degree camera, and an extremely refined automatic engine.",
    pros: ["Highly spacious cabin and wide boot space", "Refined 4-cylinder engine with smart hybrid technology", "Loaded with premium features like Head-up Display"],
    cons: ["Build quality could be more robust", "High-speed highway stability is average"],
  },
  {
    _id: "mock3",
    name: "Tata Punch",
    brand: "Tata",
    price: 6.1,
    onRoadPrice: 7.0,
    category: "Hatchback",
    fuelType: "Petrol",
    transmission: "Manual",
    seatingCapacity: 5,
    mileage: 20.1,
    safetyRating: 5,
    image: "/cars/punch.jpg",
    gallery: ["/cars/punch.jpg"],
    engine: "1.2L Revotron 3-Cylinder Petrol",
    horsepower: 87,
    torque: 115,
    topSpeed: 150,
    airbags: 2,
    adas: false,
    maintenanceCostPerYear: 6000,
    description: "The Tata Punch is a highly popular sub-compact SUV/Hatchback known for its robust 5-star GNCAP safety rating, commanding high seating position, and rugged road presence.",
    pros: ["Robust 5-star GNCAP verified safety rating", "High seating position with excellent road visibility", "Tough suspension handles broken roads with ease"],
    cons: ["Engine can feel noisy at high highway RPMs", "No automatic option on base variant trims"],
  },
  {
    _id: "mock4",
    name: "Tata Nexon EV",
    brand: "Tata",
    price: 14.8,
    onRoadPrice: 15.5,
    category: "EV",
    fuelType: "Electric",
    transmission: "Automatic",
    seatingCapacity: 5,
    mileage: 465,
    safetyRating: 5,
    image: "/cars/nexon-ev.jpg",
    gallery: ["/cars/nexon-ev.jpg"],
    engine: "40.5 kWh LFP Battery Pack",
    horsepower: 143,
    torque: 250,
    topSpeed: 150,
    airbags: 6,
    adas: false,
    maintenanceCostPerYear: 8000,
    description: "The Tata Nexon EV is India's highest selling electric SUV, housing a high-capacity 40.5 kWh IP67 certified battery pack, offering a real-world single-charge range of 465 km alongside standard fast charging.",
    pros: ["Ultra-low daily electric running expenses", "Robust 5-star GNCAP verified safety rating", "Instant torque and highly silent driving response"],
    cons: ["Public charging network is still growing in remote areas", "Firm ride suspension over broken roads"],
  },
  {
    _id: "mock5",
    name: "Tata Punch EV",
    brand: "Tata",
    price: 10.9,
    onRoadPrice: 11.5,
    category: "EV",
    fuelType: "Electric",
    transmission: "Automatic",
    seatingCapacity: 5,
    mileage: 315,
    safetyRating: 5,
    image: "/cars/punch.jpg",
    gallery: ["/cars/punch.jpg"],
    engine: "25 kWh High-Density LFP Battery",
    horsepower: 80,
    torque: 114,
    topSpeed: 140,
    airbags: 6,
    adas: false,
    maintenanceCostPerYear: 6500,
    description: "The Tata Punch EV is a highly advanced micro electric SUV built on the new active.ev platform, featuring a 25 kWh battery, 315 km range, standard 6 airbags, and a premium cabin layout.",
    pros: ["Highly affordable premium electric SUV", "Excellent 315 km single-charge driving range", "Loaded with electric options like multi-mode regeneration"],
    cons: ["Infotainment screens can have minor lag", "Boot space is compromised by the spare wheel setup"],
  },
  {
    _id: "mock6",
    name: "Hyundai Creta",
    brand: "Hyundai",
    price: 11.0,
    onRoadPrice: 12.8,
    category: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    seatingCapacity: 5,
    mileage: 16.8,
    safetyRating: 4,
    image: "/cars/creta.jpg",
    gallery: ["/cars/creta.jpg"],
    engine: "1.5L MPi 4-Cylinder Petrol DOHC",
    horsepower: 113,
    torque: 144,
    topSpeed: 170,
    airbags: 6,
    adas: true,
    maintenanceCostPerYear: 11000,
    description: "The Hyundai Creta is India's most beloved family SUV. Providing premium features like a panoramic sunroof, ventilated front seats, smart air purifiers, and level 2 ADAS safety.",
    pros: ["Exceptional ride comfort and smooth suspension", "Features list is packed: Panoramic Sunroof, Ventilated Seats", "Refined, silent engine performance with smooth CVT shifts"],
    cons: ["Styling can feel polarising to some buyers", "Slightly less steering feedback at high highway speeds"],
  },
  {
    _id: "mock7",
    name: "Kia Sonet",
    brand: "Kia",
    price: 8.2,
    onRoadPrice: 9.3,
    category: "SUV",
    fuelType: "Petrol",
    transmission: "Manual",
    seatingCapacity: 5,
    mileage: 18.4,
    safetyRating: 4,
    image: "/cars/sonet.jpg",
    gallery: ["/cars/sonet.jpg"],
    engine: "1.2L Smartstream 4-Cylinder Petrol",
    horsepower: 82,
    torque: 115,
    topSpeed: 160,
    airbags: 6,
    adas: false,
    maintenanceCostPerYear: 7000,
    description: "The Kia Sonet is a highly stylish compact SUV equipped with premium segment-first features like ventilated seats, smart connectivity, and a bold aggressive tiger-nose grille.",
    pros: ["Aggressive sporty exterior design with high road stance", "Premium segment-first ventilated front seat comfort", "Excellent build quality with 6 standard airbags"],
    cons: ["Rear legroom is slightly cramped compared to competitors", "Ride can feel slightly stiff on sharp potholes"],
  },
  {
    _id: "mock8",
    name: "Kia Seltos",
    brand: "Kia",
    price: 11.5,
    onRoadPrice: 13.2,
    category: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    seatingCapacity: 5,
    mileage: 17.2,
    safetyRating: 3,
    image: "/cars/seltos.jpg",
    gallery: ["/cars/seltos.jpg"],
    engine: "1.5L Turbocharged Petrol Engine",
    horsepower: 158,
    torque: 253,
    topSpeed: 185,
    airbags: 6,
    adas: true,
    maintenanceCostPerYear: 11500,
    description: "The Kia Seltos is a futuristic midsize SUV featuring a dual 10.25-inch panoramic display screen, advanced ADAS suite, and a highly powerful 158 HP turbo-petrol engine.",
    pros: ["Ultra-powerful turbocharged engine performance", "Sleek dual-screen driver cockpit dashboard setup", "Excellent high speed highway stability"],
    cons: ["Stiff suspension setup on bumpy city roads", "Average GNCAP safety crash rating"],
  },
  {
    _id: "mock9",
    name: "Mahindra Thar",
    brand: "Mahindra",
    price: 12.8,
    onRoadPrice: 14.5,
    category: "SUV",
    fuelType: "Diesel",
    transmission: "Manual",
    seatingCapacity: 4,
    mileage: 15.2,
    safetyRating: 4,
    image: "/cars/thar.jpg",
    gallery: ["/cars/thar.jpg"],
    engine: "2.2L mHawk Turbocharged Diesel",
    horsepower: 130,
    torque: 300,
    topSpeed: 155,
    airbags: 2,
    adas: false,
    maintenanceCostPerYear: 14000,
    description: "The Mahindra Thar is India's ultimate off-road icon, featuring standard 4x4 drivetrains, removable roof panels, massive ground clearance, and an imposing road presence.",
    pros: ["Legendary off-road capabilities with robust 4x4", "Imposing muscular road presence", "Powerful diesel torque delivery"],
    cons: ["Bumpy ride quality inside city limits", "Narrow rear seating for 4 passengers only"],
  },
  {
    _id: "mock10",
    name: "Mahindra XUV700",
    brand: "Mahindra",
    price: 14.5,
    onRoadPrice: 16.8,
    category: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    seatingCapacity: 7,
    mileage: 15.0,
    safetyRating: 5,
    image: "/cars/xuv700.jpg",
    gallery: ["/cars/xuv700.jpg"],
    engine: "2.2L mHawk Turbocharged Diesel",
    horsepower: 182,
    torque: 450,
    topSpeed: 190,
    airbags: 7,
    adas: true,
    maintenanceCostPerYear: 16000,
    description: "The Mahindra XUV700 is India's premier luxury-level family SUV, hosting a robust mHawk diesel engine paired with ADAS safety technologies and dual screen dashboards.",
    pros: ["Spacious and premium 3-row cabin luxury", "Advanced Level 2 ADAS active safety verified", "Highly powerful mHawk diesel torque push"],
    cons: ["Slightly lower diesel fuel economy in peak traffic", "Long booking delivery waiting periods in some cities"],
  },
  {
    _id: "mock11",
    name: "MG Astor",
    brand: "MG",
    price: 9.8,
    onRoadPrice: 11.2,
    category: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    seatingCapacity: 5,
    mileage: 14.8,
    safetyRating: 5,
    image: "/cars/astor.jpg",
    gallery: ["/cars/astor.jpg"],
    engine: "1.5L VTi-TECH DOHC Petrol",
    horsepower: 108,
    torque: 144,
    topSpeed: 170,
    airbags: 6,
    adas: true,
    maintenanceCostPerYear: 9500,
    description: "The MG Astor is a highly premium midsize SUV featuring personal AI assistant robots on the dashboard, luxury soft-touch leather interiors, and robust level 2 ADAS safety.",
    pros: ["Ultra-premium interior cabin dashboard soft leather", "Interactive personal AI assistant robot integrated", "Smooth, refined automatic ride quality"],
    cons: ["Mileage is slightly lower in peak city driving", "Engine power can feel average on steep hill climbs"],
  },
  {
    _id: "mock12",
    name: "MG Hector",
    brand: "MG",
    price: 15.2,
    onRoadPrice: 17.5,
    category: "SUV",
    fuelType: "Diesel",
    transmission: "Manual",
    seatingCapacity: 5,
    mileage: 15.5,
    safetyRating: 5,
    image: "/cars/hactor.jpg",
    gallery: ["/cars/hactor.jpg"],
    engine: "2.0L Multijet Turbo Diesel",
    horsepower: 168,
    torque: 350,
    topSpeed: 180,
    airbags: 6,
    adas: true,
    maintenanceCostPerYear: 13000,
    description: "The MG Hector is India's premium internet-connected SUV, featuring a massive portrait 14-inch touchscreen console, electric tailgate, panoramic sunroof, and a strong fiat-sourced diesel motor.",
    pros: ["Massive 14-inch portrait touchscreen dashboard console", "Rear legroom is unmatched in the segment", "Smooth power delivery from the diesel engine"],
    cons: ["Soft suspension causes body roll on fast corners", "No automatic gearbox option on the diesel trim"],
  },
  {
    _id: "mock13",
    name: "MG ZS EV",
    brand: "MG",
    price: 18.9,
    onRoadPrice: 19.8,
    category: "EV",
    fuelType: "Electric",
    transmission: "Automatic",
    seatingCapacity: 5,
    mileage: 461,
    safetyRating: 5,
    image: "/cars/zs-ev.jpg",
    gallery: ["/cars/zs-ev.jpg"],
    engine: "50.3 kWh Prismatic Li-ion Battery",
    horsepower: 174,
    torque: 280,
    topSpeed: 165,
    airbags: 6,
    adas: true,
    maintenanceCostPerYear: 9000,
    description: "The MG ZS EV is a premium midsize electric SUV featuring a 50.3 kWh battery pack, level 2 ADAS active safety features, panoramic sunroof, and full digital dashboard cockpit.",
    pros: ["Exceptional 461 km certified range pack", "Highly premium soft touch interior layout", "Standard level 2 active ADAS safety features"],
    cons: ["Slightly higher entry price point in segment", "Middle passenger seat belt design can be improved"],
  },
  {
    _id: "mock14",
    name: "Renault Triber",
    brand: "Renault",
    price: 6.3,
    onRoadPrice: 7.2,
    category: "Hatchback",
    fuelType: "Petrol",
    transmission: "Manual",
    seatingCapacity: 7,
    mileage: 18.2,
    safetyRating: 4,
    image: "/cars/swift.jpg",
    gallery: ["/cars/swift.jpg"],
    engine: "1.0L Energy 3-Cylinder Petrol",
    horsepower: 71,
    torque: 96,
    topSpeed: 140,
    airbags: 4,
    adas: false,
    maintenanceCostPerYear: 6000,
    description: "The Renault Triber is a highly versatile 7-seater family hatchback/MPV under 4 meters, offering modular removable third-row seating, a massive boot space, and 4-star safety.",
    pros: ["Most affordable 7-seater family car in India", "Highly modular seating with fully removable 3rd row", "Impressive 4-star safety rating"],
    cons: ["Engine can feel underpowered under full passenger load", "No automatic option in top diesel/petrol variants"],
  },
  {
    _id: "mock15",
    name: "Honda Elevate",
    brand: "Honda",
    price: 11.7,
    onRoadPrice: 13.5,
    category: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    seatingCapacity: 5,
    mileage: 16.9,
    safetyRating: 5,
    image: "/cars/elevate.jpg",
    gallery: ["/cars/elevate.jpg"],
    engine: "1.5L i-VTEC 4-Cylinder Petrol Engine",
    horsepower: 119,
    torque: 145,
    topSpeed: 175,
    airbags: 6,
    adas: true,
    maintenanceCostPerYear: 8500,
    description: "The Honda Elevate is a robust, highly reliable midsize family SUV based on the legendary Honda City platform, offering an ultra-refined i-VTEC engine, Honda Sensing ADAS, and superb ride comfort.",
    pros: ["Ultra-reliable and refined i-VTEC petrol motor", "Honda Sensing active ADAS safety features", "Massive ground clearance and huge cargo trunk space"],
    cons: ["No hybrid or diesel fuel option available", "Cabin insulation can let in road noise at high speed"],
  },
  {
    _id: "mock16",
    name: "BYD Atto 3",
    brand: "BYD",
    price: 24.9,
    onRoadPrice: 25.8,
    category: "EV",
    fuelType: "Electric",
    transmission: "Automatic",
    seatingCapacity: 5,
    mileage: 521,
    safetyRating: 5,
    image: "/cars/zs-ev.jpg",
    gallery: ["/cars/zs-ev.jpg"],
    engine: "60.48 kWh BYD Blade Battery Pack",
    horsepower: 201,
    torque: 310,
    topSpeed: 160,
    airbags: 7,
    adas: true,
    maintenanceCostPerYear: 9800,
    description: "The BYD Atto 3 is a premium electric SUV featuring the revolutionary ultra-safe BYD Blade Battery, producing 201 HP, 521 km range, Level 2 ADAS, and a highly unique fitness-inspired cabin styling.",
    pros: ["Revolutionary Blade Battery offers unmatched thermal safety", "Stellar 521 km single charge range", "High-performance motor pushing 201 HP and 310 Nm"],
    cons: ["Interior design theme can feel overly futuristic to some", "Higher price point in standard catalog segment"],
  }
];

export const MOCK_EXPLORER_CARS = MOCK_CARS;
export const ALL_CARS_POOL = MOCK_CARS;

export const MOCK_CAR_DETAILS = MOCK_CARS.reduce((acc, car) => {
  acc[car._id] = car;
  return acc;
}, {});
